<div id="footer">
    <div id="full-footer">
        <div id="footer-left" class="footer-vert-divider-right">
            <h3>Popular Destinations</h3>
            <div id="popular-left">
                <ul>
                    <li><a href="http://www.flipkey.com/breckenridge-vacation-rentals/g33327/">Breckenridge</a></li>
                    <li><a href="http://www.flipkey.com/cape-cod-vacation-rentals/g185492/">Cape Cod</a></li>
                    <li><a href="http://www.flipkey.com/destin-vacation-rentals/g34182/">Destin</a></li>
                    <li><a href="http://www.flipkey.com/disney-orlando-vacation-rentals/g1553643/">Disney-Orlando</a></li>
                    <li><a href="http://www.flipkey.com/gatlinburg-vacation-rentals/g60842/">Gatlinburg</a></li>
                    <li><a href="http://www.flipkey.com/gulf-shores-vacation-rentals/g30582/">Gulf Shores</a></li>
                    <li><a href="http://www.flipkey.com/hilton-head-vacation-rentals/g54273/">Hilton Head</a></li>
                    <li><a href="http://www.flipkey.com/kauai-vacation-rentals/g29218/">Kauai</a></li>
                    <li><a href="http://www.flipkey.com/key-west-vacation-rentals/g34345/">Key West</a></li>
                    <li><a href="http://www.flipkey.com/maui-vacation-rentals/g29220/">Maui</a></li>
                </ul>
            </div>
            <div id="popular-right">
                <ul>
                    <li><a href="http://www.flipkey.com/myrtle-beach-grand-strand-area-vacation-rentals/g1553722/">Myrtle Beach</a></li>
                    <li><a href="http://www.flipkey.com/naples-vacation-rentals/g34467/">Naples</a></li>
                    <li><a href="http://www.flipkey.com/oahu-vacation-rentals/g29222/">Oahu</a></li>
                    <li><a href="http://www.flipkey.com/ocean-city-vacation-rentals/g41298/">Ocean City</a></li>
                    <li><a href="http://www.flipkey.com/outer-banks-vacation-rentals/g616326/">Outer Banks</a></li>
                    <li><a href="http://www.flipkey.com/panama-city-beach-vacation-rentals/g34543/">Panama City Beach</a></li>
                    <li><a href="http://www.flipkey.com/san-diego-county-vacation-rentals/g1553627/">San Diego</a></li>
                    <li><a href="http://www.flipkey.com/lake-tahoe-vacation-rentals/g155987/">Lake Tahoe</a></li>
                    <li><a href="http://www.flipkey.com/tybee-island-vacation-rentals/g35328/">Tybee Island</a></li>
                    <li><a href="http://www.flipkey.com/virginia-beach-vacation-rentals/g58277/">Virginia Beach</a></li>
                </ul>
            </div>
        </div>
        <div id="footer-middle-left" class="footer-vert-divider-left footer-vert-divider-right">
            <div class="footer-horiz-divider-top">
                <h3>Explore FlipKey</h3>
                <ul>
                    <li><a href="http://www.flipkey.com/vacation-rentals/">Find a vacation rental</a></li>
                    <li><a href="http://www.flipkey.com/galleries">Galleries</a></li>
                    <li><a href="http://www.flipkey.com/list/">List your property</a></li>
                </ul>
            </div>
            <div class="footer-horiz-divider-bottom">
                <h3>FlipKey Elsewhere</h3>
                <a href="http://www.facebook.com/flipkey" rel="nofollow"><div id="footer-facebook" class="general-facebook"></div></a>
                <a href="http://www.twitter.com/flipkey" rel="nofollow"><div id="footer-twitter" class="general-twitter"></div></a>
                <a href="http://feeds.feedburner.com/FlipkeyBlog" rel="nofollow"><div id="footer-rss" class="general-rss"></div></a>
                <div class="cleaner"></div>
            </div>
        </div>
        <div id="footer-middle-right" class="footer-vert-divider-left footer-vert-divider-right">
            <h3>About Us</h3>
            <ul>
                <li><a href="http://www.flipkey.com/blog/">Blog</a></li>
                <li><a href="http://www.flipkey.com/Pages/about_us/">About FlipKey</a></li>
                <li><a href="http://www.flipkey.com/Pages/careers/">Careers</a></li>
                <li><a href="http://www.flipkey.com/Pages/contact/">Contact us</a></li>
                <li><a href="http://www.flipkey.com/Pages/management/">Management</a></li>
                <li><a href="http://www.flipkey.com/Pages/media/">Press &amp; Media</a></li>
                <li><a href="http://www.flipkey.com/Pages/affiliates/">Affiliates</a></li>
                <li><a href="http://www.flipkey.com/Pages/terms_cond/" rel="nofollow">Terms &amp; Conditions</a></li>
            </ul>
        </div>
        <div id="footer-right" class="footer-vert-divider-left">
            <h3>New to FlipKey?</h3>
            <a href="index.html">
                <div class="new-to-flipkey"></div>
                <div id="new-to-flipkey">
                    Find the vacation rental perfect for you. <span>Learn how.</span>
                </div>
            </a>
        </div>
    </div>
</div>
<div id="copyright">
    <a href="http://www.flipkey.com/"><div class="general-logo-141px"></div></a>
    <div id="flipkey-desc">
        FlipKey is a vacation rental marketplace with more than 160,000 rentals around the world. Find the perfect place to stay for your trip, and get great value along with the space, privacy and amenities of home.
    </div>
    <div id="copyright-text">
        Copyright &copy; 2012, FlipKey Inc. All rights reserved.
    </div>
</div>