<div id="header">
    <a href="http://www.flipkey.com/" rel="home"><div id="header-logo" class="general-logo-191px"></div></a>

    <div id="header-links">
        <div id="decorator-links">
            <div id="add-property" class="decorator-link"><div class="general-add"></div><a href="http://www.flipkey.com/list/">List your property</a></div>
            <div id="change-currency" class="decorator-pane">
                <div id="selected-currency" class="decorator-link">
                    <a id="currency-selector-link" href="javascript:void(0)" onclick="FlipKey.DecoratorPane.toggle(this)">
                    <span>$ USD
                <span class="flag flag-us"></span> &#9660;</span>        </a>
                </div>
                <div id="currency-selector" class="decorator-panel">
                    <h3>Choose a currency</h3>
                    <ul class="fullwidth">
                        <li>
                            <a href="javascript:FlipKey.Currency.change('AUD');">
                                <span class="symbol">$</span>
                                <span class="code">AUD</span>
                                <span class="flag flag-au"></span>
                            </a>
                        </li>            <li>
                        <a href="javascript:FlipKey.Currency.change('BRL');">
                            <span class="symbol">R$</span>
                            <span class="code">BRL</span>
                            <span class="flag flag-br"></span>
                        </a>
                    </li>            <li>
                        <a href="javascript:FlipKey.Currency.change('CAD');">
                            <span class="symbol">$</span>
                            <span class="code">CAD</span>
                            <span class="flag flag-ca"></span>
                        </a>
                    </li>            <li>
                        <a href="javascript:FlipKey.Currency.change('CHF');">
                            <span class="symbol">fr.</span>
                            <span class="code">CHF</span>
                            <span class="flag flag-ch"></span>
                        </a>
                    </li>            <li>
                        <a href="javascript:FlipKey.Currency.change('CNY');">
                            <span class="symbol">&yen;</span>
                            <span class="code">CNY</span>
                            <span class="flag flag-cn"></span>
                        </a>
                    </li>            <li>
                        <a href="javascript:FlipKey.Currency.change('EUR');">
                            <span class="symbol">&euro; </span>
                            <span class="code">EUR</span>
                            <span class="flag flag-eu"></span>
                        </a>
                    </li>            <li>
                        <a href="javascript:FlipKey.Currency.change('GBP');">
                            <span class="symbol">&pound;</span>
                            <span class="code">GBP</span>
                            <span class="flag flag-gb"></span>
                        </a>
                    </li>            <li>
                        <a href="javascript:FlipKey.Currency.change('INR');">
                            <span class="symbol">Rs</span>
                            <span class="code">INR</span>
                            <span class="flag flag-in"></span>
                        </a>
                    </li>            <li>
                        <a href="javascript:FlipKey.Currency.change('ISK');">
                            <span class="symbol">kr</span>
                            <span class="code">ISK</span>
                            <span class="flag flag-is"></span>
                        </a>
                    </li>            <li>
                        <a href="javascript:FlipKey.Currency.change('JPY');">
                            <span class="symbol">&yen;</span>
                            <span class="code">JPY</span>
                            <span class="flag flag-jp"></span>
                        </a>
                    </li>            <li>
                        <a href="javascript:FlipKey.Currency.change('MXN');">
                            <span class="symbol">$</span>
                            <span class="code">MXN</span>
                            <span class="flag flag-mx"></span>
                        </a>
                    </li>            <li>
                        <a href="javascript:FlipKey.Currency.change('NZD');">
                            <span class="symbol">$</span>
                            <span class="code">NZD</span>
                            <span class="flag flag-nz"></span>
                        </a>
                    </li>            <li>
                        <a href="javascript:FlipKey.Currency.change('RUB');">
                            <span class="symbol">&#1088;&#1091;&#1073;</span>
                            <span class="code">RUB</span>
                            <span class="flag flag-ru"></span>
                        </a>
                    </li>            <li>
                        <a href="javascript:FlipKey.Currency.change('THB');">
                            <span class="symbol">&#3647;</span>
                            <span class="code">THB</span>
                            <span class="flag flag-th"></span>
                        </a>
                    </li>            <li>
                        <a href="javascript:FlipKey.Currency.change('ZAR');">
                            <span class="symbol">R</span>
                            <span class="code">ZAR</span>
                            <span class="flag flag-za"></span>
                        </a>
                    </li>        </ul>
                </div>
            </div>
            <script type="text/javascript">
                Event.observe(window, 'load', function() {
                    FlipKey.Currency.userCurrency = {"id":"840","code":"USD","country_code":"us","symbol":"$","name":"US Dollar","minor_name":"Cent","minor_units":"100","charset":"latin-1","format":"[n-][$][M,3][m.2]","rounding":"0.005=0.01","abbreviation":"1=1","modified":"2011-11-28 00:00:00","supported":"1","exchange_rate":1,"exchangeRate":1};
                });
            </script>                        <div id="help" class="decorator-link"><a href="http://www.flipkey.com/learn_more/basics/">Help</a></div>
            <div id="register" class="decorator-link"><a href="http://www.flipkey.com/users/register/">Register</a></div>
            <div id="sign-in" class="decorator-link"><a href="javascript:void(0);" id="login-link" rel="nofollow">Sign in</a></div>
            <div class="cleaner"></div>
        </div>

        <div id="new-to-flipkey">
            <span>New to vacation rentals?</span> <a href="index.html">Start here.</a>
        </div>
    </div>
</div>