<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"
      xmlns:og="http://ogp.me/ns#"
      xmlns:fb="http://www.facebook.com/2008/fbml">
<head>
    <?php
    // Title
    echo $this->headTitle($this->translate('Vacation Rentals - FlipKey - How it works'))->setSeparator(' - ')->setAutoEscape(false);

    // Meta
    echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');
    echo $this->headMeta()->appendName('revisit-after', '5 days');

    // Styles
    echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/ccss/traveler_c.css%3Fver=2183.css')
        ->prependStylesheet($this->basePath() . '/ccss/base_c.css%3Fver=2183.css');

    // Scripts
    echo $this->headScript()->prependFile($this->basePath() . '/cjs/roundies.js%3Fver=2183', 'text/javascript', array('conditional' => 'lt IE 7',))
        ->prependFile($this->basePath() . '/cjs/traveler_c.js%3Fver=2183')
        ->prependFile($this->basePath() . '/cjs/base_c.js%3Fver=2183');


    echo $this->render('layout/header/head_js')
    ?>
</head>
<body>
    <div id="arches" >
        <div id="arches-full">
            <div id="alert-bar-top" class="alert-bar"></div>
            <div id="full-width-top-decorator"></div>
            <?= $this->render('layout/header') ?>
            <?= $this->render('layout/header/navbar') ?>
            <?= $this->render('layout/header/mypicks') ?>
            <?= $this->render('layout/header/login_box') ?>

            <div id="moab">
                <div id="content">
                    <a class="brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Skeleton Application') ?></a>
                    <?php echo $this->content; ?>
                </div>
            </div>

            <?= $this->render('layout/footer') ?>
        </div>
    </div>
    <input id='ioBB' name='data[BB][iobb]' type='hidden' />
    <?php echo $this->inlineScript() ?>
</body>
</html>
