<script type="text/javascript">
    FlipKey = {"controller":"pages","action":"how_it_works_new","debug":0};
    document.documentElement.className += " js";
</script>
<script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-2268929-1']);
    _gaq.push(['_setDomainName', '.flipkey.com']);
    _gaq.push(['_setSiteSpeedSampleRate', 7]);
    _gaq.push(['_trackPageview']);

    // Wrapped in anon function to avoid naming conflicts
    (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(ga);
    })();
</script>