<div id="" style="display:none">
</div>
<div id="my-picks-details-outer" style="display:none;">
    <div id="my-picks-details">
        <table>
            <tr>
                <td style="width: 707px; height: 100%" class="nav_content_wrapper" valign="middle">
                    <div id="mypicks_nav_content" style="display:none;"></div>
                    <div id="views_nav_content" style="display:none;"></div>
                    <div id="inquiries_nav_content" style="display:none;"></div>
                </td>
                <td style="width: 235px; height: 100%;">
                    <table class="my-picks-nav-menu">
                        <tr>
                            <td class="grey-trim"></td>
                        </tr>
                        <td class="nav-li" id="mypicks_nav_tab" onclick="FlipKey.MyPicks.make_active('mypicks');">My Picks <span class="numbers" >(0)</span> <span id="mypicks_links" class="share_links" style="display:none;"><a href="http://www.flipkey.com/search/my_picks/">View All</a></span></td>
                        <tr>
                            <td class="nav-li" id="views_nav_tab" onclick="FlipKey.MyPicks.make_active('views');">Recently Viewed <span class="numbers" > (0)</span> <span id="views_links" class="share_links" style="display:none;"><a href="http://www.flipkey.com/search/viewed/">View All</a></span></td>
                        </tr>
                        <tr>
                            <td class="nav-li" id="inquiries_nav_tab" onclick="FlipKey.MyPicks.make_active('inquiries');">Inquired Upon <span class="numbers" > (0)</span> <span id="inquiries_links" class="share_links" style="display:none;"><a href="http://www.flipkey.com/search/inquired/">View All</a></span></td>
                        </tr>
                    </table>
                </td>
                <td style="width: 10px; height: 100%;" class="grey-trim"></td>
            </tr>
        </table>
    </div>
</div>